### ISSUE TITLE
There is a hard limit of 20 assistants after which we assistants that are created are not listed and not usable for chats.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/rubra#39]
**Steps to reproduce the problem:**
1. Create 20 assistant.
2. Create 1 more assistant.
3. This assistant is not getting listed in the "chat" or "Explore Assistants" page

**Expected Behavior:**
Should be able to list the assistant created and use it for chat.

**Comment by sanjay920** [comment]
@sangee2004 I believe this was resolved with https://github.com/acorn-io/rubra/commit/bc4006577d1852a8974f218e706a356b614c824d

**Comment by sangee2004** [comment]
This issue is not seen any more when testing with latest rubra installs.
Able to work with and create more assistants when there are more than 20 of them.
