### ISSUE TITLE
Not able to display strings which have ":" in chat window properly.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/rubra#44]
**Steps to reproduce the problem:**
1. Request for query that has ":"  like "Get info on image nginx:v0.0.1"

This gets displayed with ":v0" lost and a new line introduced between the strings

<img width="1135" alt="Screen Shot 2024-02-13 at 3 31 53 PM" src="https://github.com/acorn-io/rubra/assets/122560863/bcbfafab-a10a-426f-8ba1-703dce992ada">

Note - Query sent to LLM does not have any character lost . Issue is seen only in the chat window.

**Comment by sanjay920** [comment]
I was able to replicate the issue on my end. It was because of the way streamlit renders markdown: https://github.com/streamlit/streamlit/issues/7795

https://github.com/acorn-io/rubra/commit/a54dd7e79c17cff4c2233edae97066dc9ff7dfff fixes this

**Comment by sangee2004** [comment]
This issue is not seen any more when testing with latest rubra installs.
